# Generated by Django 3.2.5 on 2021-07-11 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('ticket', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=120)),
                ('arival', models.CharField(max_length=120)),
                ('adult', models.BigIntegerField()),
                ('child', models.BigIntegerField()),
                ('totalcost', models.BigIntegerField()),
                ('departureDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('payment', models.CharField(max_length=120)),
                ('fromP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fromPBT', to='SkyTravel.places')),
                ('toP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toPBT', to='SkyTravel.places')),
                ('tripType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SkyTravel.triptype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=120)),
                ('arival', models.CharField(max_length=120)),
                ('adultcost', models.BigIntegerField()),
                ('childcost', models.BigIntegerField()),
                ('fromP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fromPB', to='SkyTravel.places')),
                ('toP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toPB', to='SkyTravel.places')),
            ],
        ),
        migrations.CreateModel(
            name='AirTrip',
            fields=[
                ('ticket', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=120)),
                ('arival', models.CharField(max_length=120)),
                ('adult', models.BigIntegerField()),
                ('child', models.BigIntegerField()),
                ('totalcost', models.BigIntegerField()),
                ('departureDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('payment', models.CharField(max_length=120)),
                ('fromP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fromPAT', to='SkyTravel.places')),
                ('toP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toPAT', to='SkyTravel.places')),
                ('tripType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SkyTravel.triptype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=120)),
                ('arival', models.CharField(max_length=120)),
                ('adultcost', models.BigIntegerField()),
                ('childcost', models.BigIntegerField()),
                ('fromP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fromPA', to='SkyTravel.places')),
                ('toP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toPA', to='SkyTravel.places')),
            ],
        ),
    ]
