# Generated by Django 3.2.5 on 2021-07-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyTravel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtrip',
            name='baby',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bustrip',
            name='baby',
            field=models.BigIntegerField(default=1),
        ),
    ]
