# Generated by Django 3.2.5 on 2021-07-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyTravel', '0004_alter_bustrip_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airchart',
            name='arival',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='airchart',
            name='departure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='airtrip',
            name='arival',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='airtrip',
            name='departure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='buschart',
            name='arival',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='buschart',
            name='departure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='arival',
            field=models.TimeField(),
        ),
    ]
