# Generated by Django 3.2.5 on 2021-07-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyTravel', '0005_auto_20210711_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airchart',
            name='adultcost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airchart',
            name='childcost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airtrip',
            name='totalcost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='buschart',
            name='adultcost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='buschart',
            name='childcost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='totalcost',
            field=models.FloatField(),
        ),
    ]
