# Generated by Django 3.2.5 on 2021-07-11 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SkyTravel', '0006_auto_20210711_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airchart',
            name='fromP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPA', to='SkyTravel.places'),
        ),
        migrations.AlterField(
            model_name='airchart',
            name='toP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toPA', to='SkyTravel.places'),
        ),
        migrations.AlterField(
            model_name='airtrip',
            name='fromP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPAT', to='SkyTravel.places'),
        ),
        migrations.AlterField(
            model_name='airtrip',
            name='toP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toPAT', to='SkyTravel.places'),
        ),
        migrations.AlterField(
            model_name='airtrip',
            name='tripType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkyTravel.triptype'),
        ),
        migrations.AlterField(
            model_name='airtrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buschart',
            name='fromP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPB', to='SkyTravel.places'),
        ),
        migrations.AlterField(
            model_name='buschart',
            name='toP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toPB', to='SkyTravel.places'),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='fromP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPBT', to='SkyTravel.places'),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='toP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toPBT', to='SkyTravel.places'),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='tripType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkyTravel.triptype'),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
