# Generated by Django 3.2.5 on 2021-07-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyTravel', '0007_auto_20210711_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtrip',
            name='tripType',
        ),
        migrations.RemoveField(
            model_name='bustrip',
            name='tripType',
        ),
        migrations.AlterField(
            model_name='airchart',
            name='arival',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='airchart',
            name='departure',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='TripType',
        ),
    ]
