# Generated by Django 3.2.5 on 2021-07-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkyTravel', '0011_auto_20210711_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bustrip',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='bustrip',
            name='user',
        ),
        migrations.DeleteModel(
            name='AirTrip',
        ),
        migrations.DeleteModel(
            name='BusTrip',
        ),
    ]
