# Generated by Django 3.2.5 on 2021-07-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyTravel', '0015_auto_20210714_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airchart',
            name='arival',
            field=models.TimeField(max_length=120),
        ),
        migrations.AlterField(
            model_name='airchart',
            name='departure',
            field=models.TimeField(max_length=120),
        ),
    ]
